"""empty message

Revision ID: 448548fd949a
Revises: 319554ea81a4
Create Date: 2021-03-11 08:53:53.176088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448548fd949a'
down_revision = '319554ea81a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=64), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_types')
    # ### end Alembic commands ###
