"""empty message

Revision ID: 5ac3ac59da92
Revises: 1b22871f9fdd
Create Date: 2021-03-13 16:49:11.391218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac3ac59da92'
down_revision = '1b22871f9fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('color', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_types', 'color')
    # ### end Alembic commands ###
